name: Generate Snake Animation

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente Ã  meia-noite (UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ Gerar animaÃ§Ã£o da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: DurezahGeek
          outputs: |
            ./output/github-contribution-grid-snake.svg
          # CustomizaÃ§Ãµes visuais:
          snake_color: "#800080"                # Roxo
          contribution_color: "#32CD32"         # Verde fixo nos dias com contribuiÃ§Ã£o
          background: "#1a1a1a"                 # Preto clarÃ­ssimo para os dias sem contribuiÃ§Ã£o
          transparent: false                    # Evita fundo branco, usa a cor definida acima

      - name: ğŸ“¤ Commitar arquivo gerado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "ğŸ Atualizando animaÃ§Ã£o da cobrinha"
          add: 'output/github-contribution-grid-snake.svg'
          github_token: ${{ secrets.GH_TOKEN }}


